version: '3.8'

services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    hostname: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - AWS_REGION=us-east-1
      - LOCALSTACK_HOST=localstack
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - INIT_SCRIPTS_PATH=/etc/localstack/init/ready.d
    volumes:
      - ./init-localstack.sh:/etc/localstack/init/ready.d/init-localstack.sh
    networks:
      - localstack_network

  app:
    build: .
    image: challenge-mindata-w2m:1.0
    environment:
      - AWS_ENDPOINT_URL=http://localstack:4566
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
    depends_on:
      - localstack
    ports:
      - "8080:8080"
    networks:
      - localstack_network
    entrypoint: ["/bin/sh", "-c", "until curl -s http://localstack:4566/_localstack/health | grep '\"sqs\": \"running\"' > /dev/null; do echo 'Waiting for LocalStack...'; sleep 2; done; echo 'LocalStack is ready'; exec java -jar usr/app/challenge-mindata-w2m-0.0.1.jar"]

networks:
  localstack_network:
    driver: bridge
