spring:
  liquibase:
    change-log: classpath:liquibase/liquibase-changelog.yml
    enabled: true
  cloud:
    aws:
      region:
        static: us-east-1
      credentials:
        access-key: test
        secret-key: test
      messaging:
        enabled: false
      sqs:
        endpoint: http://localstack:4566

aws:
  sqs:
    queue-url: http://sqs.us-east-1.localstack:4566/000000000000/sae1-spaceship-dev

logging:
  level:
    com:
      project:
        challenge: INFO
    org:
      springframework: INFO

consumer:
  spaceship:
    queue: sae1-spaceship-dev
    message-visibility-seconds: 60
    polling-interval-seconds: 2

